# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        REACT_APP_GOOGLE_API_KEY: ${{ secrets.GOOGLE_MAP_API_KEY }}
    - run: npm ci
    - run: npx ionic build --prod
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        # Deployment destination server & path. Formatted as protocol://domain.com:port/full/destination/path/
        ftp-server: ${{ secrets.FTP_STAYOPEN_SERVER }}
        ftp-username: ${{ secrets.FTP_STAYOPEN_USER }}
        ftp-password: ${{ secrets.FTP_STATOPEN_PW }}
        local-dir: build
        git-ftp-args: --all
